weddingPlanner_project/Models/Wedding.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace weddingPlanner_project.Models
{
    public class Wedding
    {
        public int UserID { get; set; }
        public int WeddingID { get; set; }
        public string Bride { get; set; }
        public string Groom { get; set; }

        public DateTime Date { get; set; }

        public string Address { get; set; }

        public List<Guest> Attending { get; set; }

        public DateTime createdat { get; set; }
        public DateTime updatedat { get; set; }


        public Wedding(){

            Attending = new List<Guest>();
            createdat = DateTime.Now;
            updatedat = DateTime.Now;
        }
    }
}

weddingPlanner_project/Models/WeddingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace weddingPlanner_project.Models
{
    public class WeddingViewModel : BaseEntity
    {
        [Required]
        public string Bride { get; set; }

        [Required]
        public string Groom { get; set; }

        [Required]
        [MyDate]
        public DateTime Date { get; set; }

        [Required]
        public string Address { get; set; }

    }
}

weddingPlanner_project/Controllers/WeddingController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using weddingPlanner_project.Models;
using Microsoft.AspNetCore.Identity;
using System.Linq;

namespace weddingPlanner_project.Controllers
{
    public class WeddingController : Controller
    {
        private YourContext _context;

            public WeddingController(YourContext context)
                
            {
                    
            _context = context;
                
            }
            [HttpGet]
            [Route("NewW")]
            public IActionResult NewW(){
                if(HttpContext.Session.GetInt32("UserID") == null){
                return RedirectToAction("Index", "Home");
            }
                return View("NewWedding");
            }

            [HttpPost]
            [Route("NewWedding")]
            public IActionResult NewWedding(WeddingViewModel model){
                if(ModelState.IsValid){

                    Wedding w = new Wedding();

                    w.Bride = model.Bride;
                    w.Groom = model.Groom;
                    w.Date = model.Date;
                    w.Address = model.Address;
                    w.createdat = DateTime.Now;
                    w.updatedat = DateTime.Now;
                    int? ID = HttpContext.Session.GetInt32("UserID");
                    int PID = (int) ID;
                    w.UserID = PID;

                    _context.Weddings.Add(w);
                    _context.SaveChanges();

                    int WeddingID = _context.Weddings.Last().WeddingID;

                    Guest g = new Guest();

                    g.UserID = PID;
                    g.WeddingID = WeddingID;

                    g.createdat = DateTime.Now;
                    g.updatedat = DateTime.Now;

                    _context.Guests.Add(g);
                    _context.SaveChanges();


                    return RedirectToAction("Dash", "Home");
                }
                else{
                    return View("NewWedding");
                }
            }
    }
}

weddingPlanner_project/Views/Wedding/NewWedding.cshtml
@model weddingPlanner_project.Models.WeddingViewModel

@{
    ViewData["Title"] = "Home Page";
}
<p style="margin-left: 450px;"><a href="/Dash">Dash</a>&emsp;<a href="/logout">Logout</a></p>
<h1>Plan Your Wedding</h1>


<form asp-controller="Wedding" asp-action="NewWedding" method="post">
    
    <span asp-validation-for="Bride"></span>
    <br>
    <label asp-for="Bride"></label>
    <input style="margin-left: 50px;" asp-for="Bride"/>
    <br>
    <br>
    <span asp-validation-for="Groom"></span>
    <br>
    <label asp-for="Groom"></label>
    <input style="margin-left: 50px;" asp-for="Groom"/>
    <br>
    <br>
    <span asp-validation-for="Date"></span>
    <br>
    <label asp-for="Date"></label>
    <input style="margin-left: 75px;" type="date" asp-for="Date"/>
    <br>
    <br>
    <span asp-validation-for="Address"></span>
    <br>
    <label asp-for="Address"></label>
    <input style="margin-left: 50px;" asp-for="Address"/>
    <br>
    <br>
    <button style="margin-left: 115px;" type="submit">Create</button>
</form>